kind: Service
apiVersion: v1
metadata:
  labels:
    app: coturn
  name: coturn
spec:
  type: NodePort
  clusterIP: 10.3.0.221
  ports:
  - { port: 3478, nodePort: 30045, name: az }
  - { port: 25000, nodePort: 30000, name: a0 }
  - { port: 25001, nodePort: 30001, name: a1 }
  - { port: 25002, nodePort: 30002, name: a2 }
  - { port: 25003, nodePort: 30003, name: a3 }
  - { port: 25004, nodePort: 30004, name: a4 }
  - { port: 25005, nodePort: 30005, name: a5 }
  - { port: 25006, nodePort: 30006, name: a6 }
  - { port: 25007, nodePort: 30007, name: a7 }
  - { port: 25008, nodePort: 30008, name: a8 }
  - { port: 25009, nodePort: 30009, name: a9 }
  selector:
    app: coturn